#!/usr/bin/env python3

import sys
import json
import requests

# User setting
icon_url = None

# Read configuration parameters
alert_file = open(sys.argv[1])
api_key = sys.argv[2]
hook_url = sys.argv[3]

# Find options
options = {}
for arg in sys.argv[4:]:
    if arg.endswith(".options"):
        with open(arg) as f:
            options = json.load(f)
        break

# Read the alert file
alert_json = json.load(alert_file)
alert_file.close()

# Content
alert_level = alert_json['rule']['level']
ruleid = alert_json['rule']['id']
description = alert_json['rule']['description']
agentid = alert_json['agent']['id']
agentname = alert_json['agent']['name']
path = alert_json.get('syscheck', {}).get('path', 'N/A')

# Arrays
exclusions = [
    [options.get('agentname_exclusion', []),agentname],
    [options.get('agentid_exclusion', []),agentid],
    [options.get('ruleid_exclusion', []),ruleid]
]
inclusions = [
    [options.get('agentname_inclusion', []),agentname],
    [options.get('agentid_inclusion', []),agentid],
    [options.get('ruleid_inclusion', []),ruleid]
]

# Eval for exclusion / inclusion

# exl[0][0] //value from options 1
# exl[0][1] //value from options 2
# exl[0][3] //value from options 3
# exl[1] //value from alert

for excl in exclusions:
    if excl[1] in excl[0]:
        sys.exit(0) # EXIT HERE

for incl in inclusions:
    if incl[1] not in incl[0] and len(incl[0]):
        sys.exit(0) # EXIT HERE

# Eval severity
if alert_level <= 11:
    priority = 'default'
    tags = 'shield'
elif alert_level <= 14:
    priority = 'high'
    tags = 'shield,warning'
else:
    priority = 'urgent'
    tags = 'shield,rotating_light'

# Create message
message = (
    "- State: " + description + "\n"
    "- Agent: " + str(agentid) + " **" + agentname + "**\n"
    "- Rule ID: " + str(ruleid) + "\n"
    "- Alert level: " + str(alert_level) + "\n"
    "- FIM alert on [`" + path + "`]"
)

# Send message
requests.post(
    hook_url,
    data=message,
    headers={
        "Authorization": "Bearer " + api_key,
        "Title": "Wazuh Alert - Rule " + str(ruleid),
        "Priority": priority,
        "Tags": tags,
        "Icon": icon_url,
        "Markdown": "yes"
    }
)

sys.exit(0)
